import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://stagingcurve.medullallc.com/');
  await page.goto('https://login.microsoftonline.com/f9b55c48-963c-4995-89c2-d5a5cd58cb7d/oauth2/v2.0/authorize?client_id=2de1baeb-9f87-432f-8e24-41d3d78bce54&scope=openid%20profile%20offline_access&redirect_uri=https%3A%2F%2Fstagingcurve.medullallc.com&client-request-id=1d696196-5aad-4c0c-821e-acfd0f6ac703&response_mode=fragment&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=2.28.0&client_info=1&code_challenge=pcRHE6bPQogcEzIc88U-mF1VmoAsexxg2CQ9GNBRd-o&code_challenge_method=S256&nonce=07c9d857-b8cb-49fd-b5f7-0a9b340dd6e5&state=eyJpZCI6IjA0MjU1YTY0LTMyM2UtNGYzNi04ZTA5LTc4MjBjYzQwNGM2OCIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3D');
  await page.goto('https://login.microsoftonline.com/f9b55c48-963c-4995-89c2-d5a5cd58cb7d/oauth2/v2.0/authorize?client_id=2de1baeb-9f87-432f-8e24-41d3d78bce54&scope=openid%20profile%20offline_access&redirect_uri=https%3A%2F%2Fstagingcurve.medullallc.com&client-request-id=1d696196-5aad-4c0c-821e-acfd0f6ac703&response_mode=fragment&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=2.28.0&client_info=1&code_challenge=pcRHE6bPQogcEzIc88U-mF1VmoAsexxg2CQ9GNBRd-o&code_challenge_method=S256&nonce=07c9d857-b8cb-49fd-b5f7-0a9b340dd6e5&state=eyJpZCI6IjA0MjU1YTY0LTMyM2UtNGYzNi04ZTA5LTc4MjBjYzQwNGM2OCIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3D&sso_reload=true');
  await page.getByPlaceholder('Email, phone, or Skype').click();
  await page.getByPlaceholder('Email, phone, or Skype').fill('Monika.Clinics_All@chiroone.net');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByLabel('Password').fill('Welcome4$');
  await page.getByLabel('Password').press('Enter');
  await page.getByRole('button', { name: 'No' }).click();
  await page.getByRole('button', { name: 'go to verification queue' }).click();
  await page.getByRole('textbox', { name: 'Search for Task ID, First' }).click();
  await page.getByRole('textbox', { name: 'Search for Task ID, First' }).fill('testfirstname 20248813236');
  await page.getByRole('textbox', { name: 'Search for Task ID, First' }).press('Enter');
  await page.getByRole('textbox', { name: 'Search for Task ID, First' }).click();
  await page.getByRole('textbox', { name: 'Search for Task ID, First' }).press('Enter');
  await page.getByText('VR24137201').click();
  await page.locator('button').filter({ hasText: 'edit' }).click();
  await page.locator('#mat-input-18').click();
  await page.locator('#mat-input-18').press('ControlOrMeta+ArrowRight');
  await page.locator('#mat-input-18').press('ControlOrMeta+ArrowRight');
  await page.locator('#mat-input-18').fill('testfirstname11');
  await page.locator('button').filter({ hasText: /^save$/ }).click();
  await page.getByRole('button', { name: 'Save Changes' }).click();
  await page.getByRole('button', { name: 'continue arrow_forward' }).click();
  await page.getByRole('button', { name: 'continue arrow_forward' }).click();
  await page.locator('#mat-input-123').click();
  await page.locator('#mat-input-123').press('ArrowRight');
  await page.locator('#mat-input-123').press('Shift+ArrowLeft');
  await page.locator('#mat-input-123').fill('1');
  await page.getByRole('button', { name: 'CALCULATE' }).click();
  await page.getByRole('button', { name: 'continue arrow_forward' }).click();
  await page.locator('.mat-slide-toggle-bar').first().click();
  await page.locator('.mat-slide-toggle-bar').first().click();
  await page.getByText('print').click();
  await page.locator('div').filter({ hasText: /^close$/ }).click();
  await page.getByLabel('Patient Total').click();
  await page.getByRole('button', { name: 'CALCULATE' }).click();
  await page.getByText('refresh').click();
  await page.getByText('2 PAYMENTS10% SAVINGS$616.00').click();
  await page.getByLabel('Open calendar').nth(1).click();
  await page.getByLabel('August 10,').click();
  await page.getByLabel('Open calendar').nth(1).click();
  await page.locator('.cdk-overlay-backdrop').click();
  await page.locator('.mat-radio-outer-circle').first().click();
  await page.getByRole('button', { name: 'GENERATE CPA' }).click();
  await page.locator('div').filter({ hasText: /^close$/ }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByText('SelectROF Outcome *').click();
  await page.getByText('Care Plan', { exact: true }).click();
  await page.locator('#upload-btn').click();
  await page.locator('#upload-btn').setInputFiles('test.pdf');
  await page.getByLabel('Open calendar').click();
  await page.getByLabel('August 8,').click();
  await page.getByRole('button', { name: 'UPDATE RCM' }).click();
  await page.goto('https://stagingcurve.medullallc.com/');
});