import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://stagingcurve.medullallc.com/');
  await page.goto('https://login.microsoftonline.com/f9b55c48-963c-4995-89c2-d5a5cd58cb7d/oauth2/v2.0/authorize?client_id=2de1baeb-9f87-432f-8e24-41d3d78bce54&scope=openid%20profile%20offline_access&redirect_uri=https%3A%2F%2Fstagingcurve.medullallc.com&client-request-id=862f56f1-c8b7-4ebc-b0ad-52186acdc62d&response_mode=fragment&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=2.28.0&client_info=1&code_challenge=qKFBK-ACPSFOjLc5sjVSey5LpgBXKMCNRUkerN04m1o&code_challenge_method=S256&nonce=e06e91e2-4155-494d-a3c8-5b9f35a2b80c&state=eyJpZCI6IjU1MGZhNThiLThmYzEtNDFkOS1hOTE1LTMwMjM4ZmNlOGQyMiIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3D');
  await page.goto('https://login.microsoftonline.com/f9b55c48-963c-4995-89c2-d5a5cd58cb7d/oauth2/v2.0/authorize?client_id=2de1baeb-9f87-432f-8e24-41d3d78bce54&scope=openid%20profile%20offline_access&redirect_uri=https%3A%2F%2Fstagingcurve.medullallc.com&client-request-id=862f56f1-c8b7-4ebc-b0ad-52186acdc62d&response_mode=fragment&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=2.28.0&client_info=1&code_challenge=qKFBK-ACPSFOjLc5sjVSey5LpgBXKMCNRUkerN04m1o&code_challenge_method=S256&nonce=e06e91e2-4155-494d-a3c8-5b9f35a2b80c&state=eyJpZCI6IjU1MGZhNThiLThmYzEtNDFkOS1hOTE1LTMwMjM4ZmNlOGQyMiIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3D&sso_reload=true');
  await page.getByPlaceholder('Email, phone, or Skype').fill('Monika.Clinics_All@chiroone.net');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByLabel('Password').fill('Welcome4$');
  await page.getByLabel('Password').press('Enter');
  await page.getByRole('button', { name: 'No' }).click();
  await page.getByRole('button', { name: 'New verification request' }).click();
  await page.getByLabel('Patient Type *').locator('span').click();
  await page.getByText('Find Existing').click();
  await page.getByLabel('Payor Type *').locator('span').click();
  await page.getByText('Health Insurance').click();
  await page.getByLabel('Verification Reason *').locator('span').click();
  await page.getByText('New Care Plan', { exact: true }).click();
  await page.locator('#mat-select-value-5').click();
  await page.getByRole('option', { name: 'Reilly' }).locator('span').click();
  await page.getByLabel('Search by Last Name, First').click();
  await page.getByRole('combobox', { name: 'Search by Last Name, First' }).click();
  await page.getByRole('combobox', { name: 'Search by Last Name, First' }).fill('20248813236 ');
  await page.getByRole('option', { name: 'testfirstname1 - 1999-12-12' }).locator('span').first().click();
  await page.getByLabel('Open calendar').click();
  await page.getByLabel('August 10,').click();
  await page.locator('#mat-select-value-7').click();
  await page.getByRole('option', { name: '7:00 AM CDT' }).locator('span').click();
  await page.getByText(':00 AM CDTReport Time (CDT) *').click();
  await page.getByText('7:15 AM CDT').click();
  await page.locator('#insurance-carrier > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').click();
  await page.getByRole('button', { name: 'WORKING RECOMMENDATIONS' }).click();
  await page.getByRole('button', { name: 'add_circle_outline Load' }).click();
  await page.getByRole('button', { name: 'WORKING RECOMMENDATIONS' }).click();
  await page.getByRole('button', { name: 'Load Previous Careplan' }).click();
  await page.locator('#mat-select-value-9').click();
  await page.getByRole('combobox', { name: 'Severity Select' }).click();
  await page.locator('.cdk-overlay-backdrop').click();
  await page.locator('#mat-select-value-9').click();
  await page.getByText('Mild Condition (VAS 1-3)').click();
  await page.getByText('SelectOnset *').click();
  await page.getByText('Acute (<6 weeks)').click();
  await page.getByText('SelectComplicating Factors *').click();
  await page.getByRole('option', { name: 'Yes' }).locator('span').click();
  await page.locator('#mat-select-value-15').click();
  await page.getByText('1-2 Regions', { exact: true }).click();
  await page.getByRole('button', { name: 'Clear' }).click();
  await page.locator('label').filter({ hasText: 'I attest to completing' }).click();
  await page.getByRole('button', { name: 'PAPERWORK' }).click();
  await page.locator('#upload-btn').click();
  await page.locator('#upload-btn').setInputFiles('test.pdf');
  await page.getByRole('button', { name: 'SUBMIT' }).click();
});