import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://stagingcurve.medullallc.com/');
  await page.goto('https://login.microsoftonline.com/f9b55c48-963c-4995-89c2-d5a5cd58cb7d/oauth2/v2.0/authorize?client_id=2de1baeb-9f87-432f-8e24-41d3d78bce54&scope=openid%20profile%20offline_access&redirect_uri=https%3A%2F%2Fstagingcurve.medullallc.com&client-request-id=43822654-d0b0-47d9-aab9-a26c71103452&response_mode=fragment&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=2.28.0&client_info=1&code_challenge=5lt5dL5d1pkJ2a33KUoNmP1XFtiYgIYVZiK2Rs2M55g&code_challenge_method=S256&nonce=bbb12929-3b05-4cd3-a1a6-3ed71e760d41&state=eyJpZCI6ImIwOGE4ZTgyLTQ4MjUtNDcxYy1hODQ3LWVlNjk0NmM0MmM3MyIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3D');
  await page.goto('https://login.microsoftonline.com/f9b55c48-963c-4995-89c2-d5a5cd58cb7d/oauth2/v2.0/authorize?client_id=2de1baeb-9f87-432f-8e24-41d3d78bce54&scope=openid%20profile%20offline_access&redirect_uri=https%3A%2F%2Fstagingcurve.medullallc.com&client-request-id=43822654-d0b0-47d9-aab9-a26c71103452&response_mode=fragment&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=2.28.0&client_info=1&code_challenge=5lt5dL5d1pkJ2a33KUoNmP1XFtiYgIYVZiK2Rs2M55g&code_challenge_method=S256&nonce=bbb12929-3b05-4cd3-a1a6-3ed71e760d41&state=eyJpZCI6ImIwOGE4ZTgyLTQ4MjUtNDcxYy1hODQ3LWVlNjk0NmM0MmM3MyIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3D&sso_reload=true');
  await page.getByPlaceholder('Email, phone, or Skype').fill('RCTMgr1@chiroone.net');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByLabel('Password').fill('Welcome4$');
  await page.getByLabel('Password').press('Enter');
  await page.getByRole('button', { name: 'No' }).click();
  await page.getByRole('button', { name: 'go to verification queue' }).click();
  await page.getByRole('textbox', { name: 'Search for Task ID, First' }).click();
  await page.getByRole('textbox', { name: 'Search for Task ID, First' }).fill('testfirstname 20248813236');
  await page.getByRole('textbox', { name: 'Search for Task ID, First' }).press('Enter');
  await page.getByText('VR24137201').click();
  await page.getByRole('button', { name: 'Take Action arrow_drop_down' }).click();
  await page.getByRole('menuitem', { name: 'Assign' }).click();
  await page.locator('#mat-select-value-9').click();
  await page.getByText('Aditya Singh').click();
  await page.getByRole('button', { name: 'ASSIGN' }).click();
  await page.getByRole('textbox', { name: 'Search for Task ID, First' }).click();
  await page.getByRole('textbox', { name: 'Search for Task ID, First' }).fill('VR24137201 ');
  await page.getByRole('textbox', { name: 'Search for Task ID, First' }).press('Enter');
  await page.getByRole('textbox', { name: 'Search for Task ID, First' }).fill('VR24137201');
  await page.getByRole('textbox', { name: 'Search for Task ID, First' }).press('Enter');
  await page.getByText('VR23049127').click();
  await page.goto('https://stagingcurve.medullallc.com/request-queue');
  await page.locator('div').filter({ hasText: /^search$/ }).nth(3).click();
  await page.getByRole('textbox', { name: 'Search for Task ID, First' }).fill('VR24137201');
  await page.getByRole('textbox', { name: 'Search for Task ID, First' }).press('Enter');
  await page.getByText('VR24137201', { exact: true }).click();
  const page5Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'OPEN ALL open_in_new' }).click();
  const page5 = await page5Promise;
  await page.getByRole('button', { name: 'continue arrow_forward' }).click();
  await page.getByRole('button', { name: 'continue arrow_forward' }).click();
  await page.getByRole('button', { name: 'continue arrow_forward' }).click();
  await page.locator('claims-status div').nth(2).click();
  await page.locator('.mat-checkbox-inner-container').click();
  await page.getByRole('button', { name: 'Continue arrow_forward' }).click();
  await page.getByLabel('Primary Fee Schedule *').locator('div').first().click();
  await page.getByText('U&C Fee').click();
  await page.getByRole('button', { name: 'CALCULATE' }).click();
  await page.getByRole('button', { name: 'SUBMIT TO CLINIC' }).click();
});